// gtube, the YouTube Music mini player on gesso. Expects the gesso repository next to this one (../gesso).
//   zig build run -- URL                   build and run
//   zig build -Doptimize=ReleaseFast -Dtarget=x86_64-windows-gnu -p zig-out/windows
const std = @import("std");

const flags: []const []const u8 = &.{ "-std=c11", "-ffp-contract=off", "-Wall", "-Wextra", "-Wno-unused-parameter", "-Wno-missing-field-initializers" };

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const gesso = b.dependency("gesso", .{ .target = target, .optimize = optimize }).artifact("gesso");

    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .strip = optimize != .Debug,
    });
    mod.addCSourceFiles(.{ .root = b.path("src"), .files = &.{ "main.c", "tools.c", "player.c", "account.c", "signin.c", "api.c", "library.c", "state.c", "viz.c", "bend_vulkan.c" }, .flags = flags });
    // The visualizer effect written in Bend: its compiler's C (generated by src/bend/build.sh), its
    // main renamed so it runs on a thread of the player, and its GPU program beside the executable.
    mod.addCSourceFile(.{ .file = b.path("src/bend/viz_bend.c"), .flags = &.{ "-std=c11", "-O3", "-w", "-DBEND_VULKAN=1", "-DBENDVIZ_EMBED", "-Dmain=bendviz_main" } });
    mod.linkLibrary(gesso);
    const exe = b.addExecutable(.{ .name = "gtube", .root_module = mod });
    b.getInstallStep().dependOn(&b.addInstallBinFile(b.path("src/bend/viz.gpu"), if (target.result.os.tag == .windows) "gtube.exe.gpu" else "gtube.gpu").step);
    if (target.result.os.tag == .windows) {
        exe.subsystem = .windows;
        for ([_][]const u8{ "ole32", "advapi32", "crypt32" }) |lib| mod.linkSystemLibrary(lib, .{});
    }
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    run.step.dependOn(b.getInstallStep());
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Build and run the player").dependOn(&run.step);
}
